var searchData=
[
  ['simplificationoptions_57',['SimplificationOptions',['../class_brain_fail_productions_1_1_poly_few_runtime_1_1_polyfew_runtime_1_1_simplification_options.html',1,'BrainFailProductions::PolyFewRuntime::PolyfewRuntime']]],
  ['simplificationstrength_58',['simplificationStrength',['../class_brain_fail_productions_1_1_poly_few_runtime_1_1_polyfew_runtime_1_1_simplification_options.html#a7dbeefd46ec1d40b7adeb1744bd9c900',1,'BrainFailProductions::PolyFewRuntime::PolyfewRuntime::SimplificationOptions']]],
  ['simplifymeshes_59',['SimplifyMeshes',['../class_brain_fail_productions_1_1_poly_few_runtime_1_1_polyfew_runtime.html#a6cb38fd4851e7ad9de49cd6dede9e2c8',1,'BrainFailProductions::PolyFewRuntime::PolyfewRuntime']]],
  ['simplifymeshlossless_60',['simplifyMeshLossless',['../class_brain_fail_productions_1_1_poly_few_runtime_1_1_polyfew_runtime_1_1_simplification_options.html#aea579184fa51007d94da7169ce4dadac',1,'BrainFailProductions::PolyFewRuntime::PolyfewRuntime::SimplificationOptions']]],
  ['simplifyobjectdeep_61',['SimplifyObjectDeep',['../class_brain_fail_productions_1_1_poly_few_runtime_1_1_polyfew_runtime.html#a0a33898f16bac353175ab96b74aaf3e0',1,'BrainFailProductions.PolyFewRuntime.PolyfewRuntime.SimplifyObjectDeep(GameObject toSimplify, SimplificationOptions simplificationOptions, Action&lt; GameObject, MeshRendererPair &gt; OnEachMeshSimplified)'],['../class_brain_fail_productions_1_1_poly_few_runtime_1_1_polyfew_runtime.html#a57098d2780c0b536443468513405f6ca',1,'BrainFailProductions.PolyFewRuntime.PolyfewRuntime.SimplifyObjectDeep(GameObject toSimplify, SimplificationOptions simplificationOptions)'],['../class_brain_fail_productions_1_1_poly_few_runtime_1_1_polyfew_runtime.html#a86f89a91056d437b5606550ed180117a',1,'BrainFailProductions.PolyFewRuntime.PolyfewRuntime.SimplifyObjectDeep(ObjectMeshPairs objectMeshPairs, SimplificationOptions simplificationOptions, Action&lt; GameObject, MeshRendererPair &gt; OnEachMeshSimplified)']]],
  ['smoothnessintensity_62',['smoothnessIntensity',['../class_brain_fail_productions_1_1_poly_few_runtime_1_1_polyfew_runtime_1_1_material_properties.html#a6ce8f75f12f108aae9d7ef5ececc6bc0',1,'BrainFailProductions::PolyFewRuntime::PolyfewRuntime::MaterialProperties']]],
  ['specularcolor_63',['specularColor',['../class_brain_fail_productions_1_1_poly_few_runtime_1_1_polyfew_runtime_1_1_material_properties.html#a30e1079abbe80f9996c367a32f2ac5fd',1,'BrainFailProductions::PolyFewRuntime::PolyfewRuntime::MaterialProperties']]]
];
